FROM python:3.8

EXPOSE 3111

COPY . /app
WORKDIR /app
RUN pip install -r techtrends/requirements.txt

# command to initialize database
RUN python techtrends/init_db.py

# command to run on container start
CMD [ "python", "app.py" ]
