FROM python:3.8

EXPOSE 3111

COPY . /app
WORKDIR /app/techtrends
RUN pip install -r requirements.txt

# command to initialize database
RUN python init_db.py

# command to run on container start
CMD [ "python", "app.py" ]
